### ISSUE TITLE
Unable to start a node

### ISSUE THREAD

**Issue by crypt0jan** [veritise/veritise-node#4]
When trying to start a node for the first time using the oneliner, or even trying to use the `config` command (which is incorrectly spelled `comfig` in the README), I get the following result:

```
powerusername@veritise:~/node$ veritise-node config -p mainnet -a dual --customPreset name.yml

2021-12-15T19:03:29.354Z info     Running image using Exec: symbolplatform/symbol-server:tools-gcc-1.0.0.0 /usr/catapult/bin/catapult.tools.votingkey --secret=HIDDEN_KEY --startEpoch=1 --endEpoch=360 --output=/votingKeys/private_key_tree1.dat

2021-12-15T19:03:30.549Z error    Unknown error generating the configuration. Command failed: docker run --rm -u 1002:1002  --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v /home/powerusername/node/target/nodes/node/votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret={{REDACTED}}" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"

2021-12-15T19:03:30.550Z error    The target folder 'target' should be deleted!!!
Error: Command failed: docker run --rm -u 1002:1002  --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v /home/powerusername/node/target/nodes/node/votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret={{REDACTED}}" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 132,
  signal: null,
  cmd: 'docker run --rm -u 1002:1002  --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v /home/powerusername/node/target/nodes/node/votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret={{REDACTED}}" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"',
  stdout: '',
  stderr: ''
}
    Error: Command failed: docker run --rm -u 1002:1002  --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v
    /home/powerusername/node/target/nodes/node/votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0
    "/usr/catapult/bin/catapult.tools.votingkey" "--secret={{REDACTED}}" "--startEpoch=1"
    "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"

    Code: 132
```

**Comment by matasvosylius** [comment]
Hey @crypt0jan, thank you for your feedback.

- Could you provide your node, docker, docker-compose versions? 
- Which operating system are you using?
